#!/bin/bash
## virtualenvwrapper/initialize
# This hook is run during the startup phase when loading virtualenvwrapper.sh.

## source the dotfiles_ functions if $__DOTFILES is set
test -n ${__DOTFILES} \
    && source ${__DOTFILES}/etc/bash/05-bashrc.dotfiles.sh \
    && dotfiles_initialize
