#!/bin/bash
# This hook is run after a new virtualenv is created and before it is activated.

## echo "dotfiles/premkvirtualenv: ${@}"
## export _VENVSTR="${1}"  # does not pass through to postmkvirtualenv

(declare -f 'dotfiles_premkvirtualenv' \ # 2>&1 > /dev/null \
    && dotfiles_premkvirtualenv "${@}") \
    || echo "dotfiles_premkvirtualenv not found" >&2

