#!/usr/bin/env bash
## 
function edit {
    #  edit()   -- EDITOR_ or EDITOR $@
    if [ -z "${GUIVIMBIN}" ]; then
        vim "${@}"
        return
    fi
    ${GUIVIMBIN} --servername ""${VIRTUAL_ENV_NAME:-"/"}"" \
        --remote-tab \
        "${@}"
    return
}

function e {
    # e()       -- EDTIOR or EDITOR $@
    edit "${@}"
    return
}

if [ -n "${BASH_SOURCE}" ] && [ "${BASH_SOURCE}" == "${0}" ]; then
    edit "${@}"
    exit
fi
