#!/bin/bash
### editvirtualenv, evirtualenv, ev   -- cd $VIRTUAL_ENV and run edit w/ each arg
function editvirtualenv {
    # editvirtualenv() -- cd $VIRTUAL_ENV and run edit w/ each arg
    (cd "${VIRTUAL_ENV}";
    (for arg in ${@}; do echo "${arg}"; done) \
        | el --each -x 'e {0}'
    )
    return
}

function evirtualenv {
    # evirtualenv()    -- cd $VIRTUAL_ENV and run edit w/ each arg
    editvirtualenv $@
    return
}

function ev {
    # ev()      -- cd $VIRTUAL_ENV and run edit w/ each arg
    editvirtualenv $@
    return
}

function _evirtualenv__complete {
    local cur=${2};
    COMPREPLY=($(cd "${VIRTUAL_ENV}"; compgen -f -- ${cur}));
}
complete -o default -o nospace -F _evirtualenv__complete editvirtualenv
complete -o default -o nospace -F _evirtualenv__complete evirtualenv
complete -o default -o nospace -F _evirtualenv__complete ev

if [[ "${BASH_SOURCE}" == "${0}" ]]; then
    editvirtualenv ${@}
    exit
fi
