#!/bin/sh
## 
editwrd () 
{
    #
    (cd $_WRD;
    (for arg in ${@}; do echo "${arg}"; done) \
        | el --each -x 'e {0}'
    )
    return
}

ew () {
    editwrd $@
    return
}
_ew__complete () {
    local cur=${2};
    COMPREPLY=($(cd ${_WRD}; compgen -f -- ${cur}));
}
complete -o default -o nospace -F _ew__complete editwrd
complete -o default -o nospace -F _ew__complete ew

if [[ ${BASH_SOURCE} == "${0}" ]]; then
    editwrd ${@}
    exit
fi
