#!/bin/bash
### editwrd, ewrd, ew   -- cd $_WRD and run edit w/ each arg
function editwrd {
    # editwrd() -- cd $_WRD and run edit w/ each arg
    (cd "${_WRD}";
    (for arg in ${@}; do echo "${arg}"; done) \
        | el --each -x 'e {0}'
    )
    return
}

function ewrd {
    # ewrd()    -- cd $_WRD and run edit w/ each arg
    editwrd $@
    return
}

function ew {
    # ew()      -- cd $_WRD and run edit w/ each arg
    editwrd $@
    return
}

function _ewrd__complete {
    local cur=${2};
    COMPREPLY=($(cd "${_WRD}"; compgen -f -- ${cur}));
}
complete -o default -o nospace -F _ewrd__complete editwrd
complete -o default -o nospace -F _ewrd__complete ewrd
complete -o default -o nospace -F _ewrd__complete ew

if [[ "${BASH_SOURCE}" == "${0}" ]]; then
    editwrd ${@}
    exit
fi
