#!/bin/bash
##

gdd() {
    (set -x; __gdd $@)
}

__gdd() {
    local GIT_OPTS="--color=always"
    local GITBIN=$(which git)

    if [ -n "${1}" ]; then
        REPO=$1
        GITBIN="${GITBIN} -C ${REPO}"
    fi
    export GIT_PAGER="less -R | cat"

    ${GITBIN} diff ${GIT_OPTS} 
    ${GITBIN} diff ${GIT_OPTS} --stat
    ${GITBIN} diff ${GIT_OPTS} --cached
    ${GITBIN} diff ${GIT_OPTS} --cached --stat
    ${GITBIN} log -n3 --stat --decorate=full ${GIT_OPTS}
    ${GITBIN} status
}

if [[ "$BASH_SOURCE" == "$0" ]]; then
  gdd $@
fi

