#!/bin/sh
### gruntw -- cd $_WRD && grunt $@ 

_gruntw() {
    # gruntw()   -- cd $_WRD && grunt $@
    (cd "${_WRD}" && grunt ${@})
}
#_gruntw_complete() {
#    local cur=${2}
#}
#complete -F _gruntw_complete gruntw

if [[ ${BASH_SOURCE} == "${0}" ]]; then
    _gruntw ${@}
    exit
fi
