#!/bin/sh
### gulpw -- cd $_WRD; gulp $@

_gulpw() {
    # gulpw()   -- cd $_WRD && gulp $@
    (cd "${_WRD}" && gulp ${@})
}
#_gulpw_complete() {
#    local cur=${2}
#}
#complete -F _gulpw_complete gulpw

if [[ ${BASH_SOURCE} == "${0}" ]]; then
    _gulpw ${@}
    exit
fi
