***************
*** 42,47 ****
  	open htmlcov/index.html
  
  
  STATIC:=./docs/_static
  LOCALJS=$(STATIC)/js/local.js
  
--- 42,50 ----
  	open htmlcov/index.html
  
  
+ BUILDDIR:=./docs/_build
+ BUILDDIRHTML:=./docs/_build/html
+ BUILDDIRSINGLEHTML:=./docs/_build/singlehtml
  STATIC:=./docs/_static
  LOCALJS=$(STATIC)/js/local.js
  
***************
*** 61,66 ****
  	cat $(STATIC)/css/sidenav-scrollto.css >> $(LOCALCSS)
  	cat $(STATIC)/css/leftnavbar.css >> $(LOCALCSS)
  
  docs-api:
  	rm -f docs/wrdrd/wrdrd.rst
  	rm -f docs/wrdrd/wrdrd.*.rst
--- 64,84 ----
  	cat $(STATIC)/css/sidenav-scrollto.css >> $(LOCALCSS)
  	cat $(STATIC)/css/leftnavbar.css >> $(LOCALCSS)
  
+ localjs-live:
+ 	$(MAKE) localjs
+ 	cp -v ${LOCALJS} ${BUILDDIRHTML}/_static/js/local.js  || true;
+ 	cp -v ${LOCALJS} ${BUILDDIRSINGLEHTML}/_static/js/local.js  || true;
+ 
+ 
+ localcss-live:
+ 	$(MAKE) localcss
+ 	cp -v ${LOCALCSS} ${BUILDDIRHTML}/_static/css/local.css || true;
+ 	cp -v ${LOCALCSS} ${BUILDDIRSINGLEHTML}/_static/css/local.css || true;
+ 
+ local-live:
+ 	$(MAKE) localjs-live
+ 	$(MAKE) localcss-live
+ 
  docs-api:
  	rm -f docs/wrdrd/wrdrd.rst
  	rm -f docs/wrdrd/wrdrd.*.rst
